package agent

import (
	"context"
	"fmt"
	"strings"

	"github.com/zayeagle/omnidev-agent/internal/llm"
	"github.com/zayeagle/omnidev-agent/internal/session"
	"github.com/zayeagle/omnidev-agent/internal/stream"
)

// ContextManager handles Cursor-style context window management.
// When estimated tokens exceed ContextMaxTokens * ContextSummarizeThreshold,
// older turns are compressed into a single "early context" summary via the LLM.
type ContextManager struct {
	maxTokens    int     // 120000 default
	threshold    float64 // 0.95 default
	provider     llm.Provider
	systemPrompt string
	retryConfig  stream.RetryConfig
}

// NewContextManager creates a context manager with the given thresholds.
func NewContextManager(provider llm.Provider, maxTokens int, threshold float64, systemPrompt string) *ContextManager {
	if maxTokens <= 0 {
		maxTokens = 120_000
	}
	if threshold <= 0 || threshold > 1 {
		threshold = 0.95
	}
	return &ContextManager{
		maxTokens:    maxTokens,
		threshold:    threshold,
		provider:     provider,
		systemPrompt: systemPrompt,
		retryConfig:  stream.DefaultRetryConfig(),
	}
}

func (cm *ContextManager) SetRetryConfig(cfg stream.RetryConfig) { cm.retryConfig = cfg }

// EstimateTokens provides a rough token count (≈ chars/3 blended).
func (cm *ContextManager) EstimateTokens(entries []session.Entry) int {
	total := 0
	for _, e := range entries {
		total += estimateEntryTokens(e)
	}
	return total
}

// UsagePercent returns estimated context fill as 0–100 (same estimator as ShouldSummarize).
func (cm *ContextManager) UsagePercent(entries []session.Entry) float64 {
	if cm.maxTokens <= 0 {
		return 0
	}
	estimated := cm.EstimateTokens(entries)
	pct := float64(estimated) / float64(cm.maxTokens) * 100
	if pct > 99.9 {
		return 99.9
	}
	if pct < 0.1 && estimated > 0 {
		return 0.1
	}
	return pct
}

// MaxTokens returns the configured context window cap.
func (cm *ContextManager) MaxTokens() int { return cm.maxTokens }

// SummarizeThreshold returns the fraction (e.g. 0.95) at which compaction triggers.
func (cm *ContextManager) SummarizeThreshold() float64 { return cm.threshold }

// ShouldSummarize returns true when the estimated token count exceeds the
// threshold percentage of the max context window.
func (cm *ContextManager) ShouldSummarize(entries []session.Entry) bool {
	estimated := cm.EstimateTokens(entries)
	limit := int(float64(cm.maxTokens) * cm.threshold)
	return estimated > limit
}

// SummarizeEarlyEntries takes the first N entries (all but the last `keepLast`
// entries) and returns a single summary entry. The summary is generated by
// calling the LLM with a summarization prompt.
//
// Returns the summary entry and an error. On failure, the caller should
// fall back to truncation (keep only recent entries).
func (cm *ContextManager) SummarizeEarlyEntries(entries []session.Entry, keepLast int) (*session.Entry, error) {
	if len(entries) <= keepLast {
		return nil, fmt.Errorf("not enough entries to summarize: %d total, %d to keep", len(entries), keepLast)
	}

	// Build a string representation of the early entries
	var sb strings.Builder
	sb.WriteString("Please summarize the following conversation history between a user and an AI coding assistant. ")
	sb.WriteString("Keep all important details: user requests, key decisions, code changes made, errors encountered, ")
	sb.WriteString("tools used and their results, and any user preferences expressed.\n\n")
	sb.WriteString("--- BEGIN HISTORY ---\n\n")

	for _, e := range entries[:len(entries)-keepLast] {
		sb.WriteString(fmt.Sprintf("[%s] %s\n", strings.ToUpper(e.Role), slimEntryForSummary(e)))
		sb.WriteString("\n")
	}
	sb.WriteString("--- END HISTORY ---\n\n")
	sb.WriteString("Provide a concise summary (keep it under 500 words). Focus on: what was requested, ")
	sb.WriteString("what was done, what decisions were made, and what remains to be done.")

	messages := []llm.Message{
		{Role: "system", Content: "You are a helpful assistant that summarizes conversations. Respond concisely in the same language as the user."},
		{Role: "user", Content: sb.String()},
	}

	resp, err := stream.RetryChat(context.Background(), cm.provider, &llm.Request{Messages: messages}, cm.retryConfig)
	if err != nil {
		return nil, err
	}

	return &session.Entry{
		Role:    "system",
		Content: "[EARLY CONTEXT SUMMARY]\n" + resp.Content,
		State:   "summarized",
		Tokens:  cm.EstimateTokens([]session.Entry{{Content: resp.Content}}),
	}, nil
}

// Compact replaces early session entries with a summary entry, keeping the
// most recent `keepLast` entries intact. Returns a new slice (does not
// mutate the original).
func (cm *ContextManager) Compact(entries []session.Entry, keepLast int) ([]session.Entry, error) {
	summary, err := cm.SummarizeEarlyEntries(entries, keepLast)
	if err != nil {
		// Fallback: keep only the last N entries
		return entries[len(entries)-keepLast:], nil
	}

	result := make([]session.Entry, 0, 1+keepLast)
	result = append(result, *summary)
	result = append(result, entries[len(entries)-keepLast:]...)
	return result, nil
}
