package agent

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf8"

	"github.com/zayeagle/omnidev-agent/internal/llm"
	"github.com/zayeagle/omnidev-agent/internal/session"
	"github.com/zayeagle/omnidev-agent/internal/stream"
)

// ContextManager handles Cursor-style context window management.
// When estimated tokens exceed ContextMaxTokens * ContextSummarizeThreshold,
// older turns are compressed into a single "early context" summary via the LLM.
type ContextManager struct {
	maxTokens   int     // 120000 default
	threshold   float64 // 0.95 default
	provider    llm.Provider
	systemPrompt string
}

// NewContextManager creates a context manager with the given thresholds.
func NewContextManager(provider llm.Provider, maxTokens int, threshold float64, systemPrompt string) *ContextManager {
	return &ContextManager{
		maxTokens:    maxTokens,
		threshold:    threshold,
		provider:     provider,
		systemPrompt: systemPrompt,
	}
}

// EstimateTokens provides a rough token count (≈ chars/4 for English, chars/1.5 for CJK-heavy).
// This is a fast heuristic, not a model-aware tokenizer. Accuracy ~±20%.
func (cm *ContextManager) EstimateTokens(entries []session.Entry) int {
	total := 0
	for _, e := range entries {
		n := utf8.RuneCountInString(e.Content)
		// Simple heuristic: 4 chars ≈ 1 token for English, 1.5 chars ≈ 1 token for CJK
		// Blend at 3 chars/token as reasonable middle ground
		total += n/3 + 1
		for _, tc := range e.ToolCalls {
			n2 := utf8.RuneCountInString(tc.Result + tc.Error)
			total += n2/3 + 1
		}
	}
	return total
}

// ShouldSummarize returns true when the estimated token count exceeds the
// threshold percentage of the max context window.
func (cm *ContextManager) ShouldSummarize(entries []session.Entry) bool {
	estimated := cm.EstimateTokens(entries)
	limit := int(float64(cm.maxTokens) * cm.threshold)
	return estimated > limit
}

// SummarizeEarlyEntries takes the first N entries (all but the last `keepLast`
// entries) and returns a single summary entry. The summary is generated by
// calling the LLM with a summarization prompt.
//
// Returns the summary entry and an error. On failure, the caller should
// fall back to truncation (keep only recent entries).
func (cm *ContextManager) SummarizeEarlyEntries(entries []session.Entry, keepLast int) (*session.Entry, error) {
	if len(entries) <= keepLast {
		return nil, fmt.Errorf("not enough entries to summarize: %d total, %d to keep", len(entries), keepLast)
	}

	// Build a string representation of the early entries
	var sb strings.Builder
	sb.WriteString("Please summarize the following conversation history between a user and an AI coding assistant. ")
	sb.WriteString("Keep all important details: user requests, key decisions, code changes made, errors encountered, ")
	sb.WriteString("tools used and their results, and any user preferences expressed.\n\n")
	sb.WriteString("--- BEGIN HISTORY ---\n\n")

	for _, e := range entries[:len(entries)-keepLast] {
		sb.WriteString(fmt.Sprintf("[%s] %s\n", strings.ToUpper(e.Role), e.Content))
		for _, tc := range e.ToolCalls {
			if tc.Error != "" {
				sb.WriteString(fmt.Sprintf("  [tool:%s] ERROR: %s\n", tc.Name, tc.Error))
			} else {
				sb.WriteString(fmt.Sprintf("  [tool:%s] %s\n", tc.Name, tc.Result))
			}
		}
		sb.WriteString("\n")
	}
	sb.WriteString("--- END HISTORY ---\n\n")
	sb.WriteString("Provide a concise summary (keep it under 500 words). Focus on: what was requested, ")
	sb.WriteString("what was done, what decisions were made, and what remains to be done.")

	messages := []llm.Message{
		{Role: "system", Content: "You are a helpful assistant that summarizes conversations. Respond concisely in the same language as the user."},
		{Role: "user", Content: sb.String()},
	}

	resp, err := stream.RetryChat(context.Background(), cm.provider, &llm.Request{Messages: messages})
	if err != nil {
		return nil, err
	}

	return &session.Entry{
		Role:    "system",
		Content: "[EARLY CONTEXT SUMMARY]\n" + resp.Content,
		State:   "summarized",
		Tokens:  cm.EstimateTokens([]session.Entry{{Content: resp.Content}}),
	}, nil
}

// Compact replaces early session entries with a summary entry, keeping the
// most recent `keepLast` entries intact. Returns a new slice (does not
// mutate the original).
func (cm *ContextManager) Compact(entries []session.Entry, keepLast int) ([]session.Entry, error) {
	summary, err := cm.SummarizeEarlyEntries(entries, keepLast)
	if err != nil {
		// Fallback: keep only the last N entries
		return entries[len(entries)-keepLast:], nil
	}

	result := make([]session.Entry, 0, 1+keepLast)
	result = append(result, *summary)
	result = append(result, entries[len(entries)-keepLast:]...)
	return result, nil
}
